# Generated by Django 4.1.7 on 2023-03-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Umri',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Baruapepe',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Jina',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Jinsia',
            new_name='name',
        ),
    ]
