# Generated by Django 4.1.7 on 2023-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject4', '0002_rename_umri_student_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
