# Generated by Django 4.1.7 on 2023-03-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject4', '0003_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Country',
            field=models.CharField(blank=True, default='Kenya', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, default=3, max_length=50),
        ),
    ]
