# Generated by Django 4.1.7 on 2023-03-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject4', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
